In [53]:
import numpy as np

In [54]:
dir(np)

['False_',
 'ScalarType',
 'True_',
 '_CopyMode',
 '_NoValue',
 '__NUMPY_SETUP__',
 '__all__',
 '__array_api_version__',
 '__array_namespace_info__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__expired_attributes__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__numpy_submodules__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_array_api_info',
 '_core',
 '_distributor_init',
 '_expired_attrs_2_0',
 '_globals',
 '_int_extended_msg',
 '_mat',
 '_msg',
 '_pyinstaller_hooks_dir',
 '_pytesttester',
 '_specific_msg',
 '_type_info',
 '_typing',
 '_utils',
 'abs',
 'absolute',
 'acos',
 'acosh',
 'add',
 'all',
 'allclose',
 'amax',
 'amin',
 'angle',
 'any',
 'append',
 'apply_along_axis',
 'apply_over_axes',
 'arange',
 'arccos',
 'arccosh',
 'arcsin',
 'arcsinh',
 'arctan',
 'arctan2',
 'arctanh',
 'argmax',
 'argmin',
 'argpartition',
 'argsort',
 'argwhere',
 'around',
 'array',
 'arr

Creating an array .

In [55]:
l =[1,4,6,8]
l

[1, 4, 6, 8]

In [56]:
arr =np.array(l)
arr

array([1, 4, 6, 8])

In [57]:
a2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
a2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [58]:
a=np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [59]:
a3=np.ones(5)
a3

array([1., 1., 1., 1., 1.])

In [60]:
a4=np.eye(3)
a4

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [61]:
ar1=np.zeros((3,3))
ar1

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [62]:
ar2=np.ones((3,3))
ar2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [63]:
ar3=np.arange(10)
ar3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
ar4=np.arange(1,11)
ar4

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [65]:
ar5=np.arange(1,11,3)
ar5

array([ 1,  4,  7, 10])

In [66]:
ar5=np.linspace(1,10,5)
ar5

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [67]:
ar6=np.full(5,3)
ar6

array([3, 3, 3, 3, 3])

In [68]:
ar7=np.full((3,3,),9)
ar7

array([[9, 9, 9],
       [9, 9, 9],
       [9, 9, 9]])

In [69]:
r1=np.random.rand(3,3,)
r1

array([[0.72775332, 0.90609649, 0.43343583],
       [0.20081646, 0.77486305, 0.41777928],
       [0.70956827, 0.69695138, 0.36058126]])

In [70]:
r2=np.random.rand(5)
r2

array([0.02583908, 0.82190901, 0.49245718, 0.72852255, 0.62840937])

In [71]:
r3=np.random.randint(5)
r3

2

In [72]:
r4=np.random.randint(3,10)
r4

5

In [73]:
r5=np.random.randint(3,10,5)
r5

array([7, 9, 6, 6, 6], dtype=int32)

In [74]:
r6=np.random.randint(3,10,(3,3))
r6

array([[4, 9, 4],
       [4, 6, 3],
       [8, 6, 5]], dtype=int32)

Indexing of arrary

In [75]:
a=np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [76]:
print(a[0])

1


In [77]:
print(a[3])

4


In [78]:
print(a[-1])

9


In [79]:
a2=np.random.randint(1,10,(3,3))
a2

array([[5, 5, 4],
       [3, 1, 9],
       [5, 5, 2]], dtype=int32)

In [80]:
print(a2[0][1])

5


In [81]:
print(a2[2][0])

5


In [82]:
print(a2[2,1])

5


Slicing of arrary

In [83]:
a=np.arange(3,10)
a

array([3, 4, 5, 6, 7, 8, 9])

In [84]:
a[0:3]

array([3, 4, 5])

In [85]:
a[-1:-5:-1]

array([9, 8, 7, 6])

In [86]:
a[2:6]

array([5, 6, 7, 8])

In [87]:
a[0::1]

array([3, 4, 5, 6, 7, 8, 9])

In [88]:
a2=np.random.randint(1,10,(3,3))
a2

array([[5, 9, 2],
       [4, 2, 9],
       [1, 5, 9]], dtype=int32)

In [89]:
a2[0:2,2]

array([2, 9], dtype=int32)

In [90]:
a2[0:,1]

array([9, 2, 5], dtype=int32)

In [91]:
a2[1,0:2]

array([4, 2], dtype=int32)

In [92]:
a2[0:,1:]

array([[9, 2],
       [2, 9],
       [5, 9]], dtype=int32)

Shape,size and datatype of arrary .

In [93]:
a

array([3, 4, 5, 6, 7, 8, 9])

In [94]:
print(a.shape)

(7,)


In [95]:
a2

array([[5, 9, 2],
       [4, 2, 9],
       [1, 5, 9]], dtype=int32)

In [96]:
print(a2.shape)

(3, 3)


In [97]:
print(a2.size)

9


In [98]:
print(a.size)

7


In [99]:
print(a.dtype)

int64


In [100]:
print(a2.dtype)

int32


Methematical operation .

In [101]:
a

array([3, 4, 5, 6, 7, 8, 9])

In [102]:
a

array([3, 4, 5, 6, 7, 8, 9])

In [103]:
print(a+a)

[ 6  8 10 12 14 16 18]


In [104]:
print(a*a)

[ 9 16 25 36 49 64 81]
