In [ ]:
import numpy as np

Mathamatical opration 

In [ ]:
a1 = np.array([1,8,6,7,9])
a1

array([1, 8, 6, 7, 9])

In [3]:
a2 = np.array([2,8,7,6,3])
a2

array([2, 8, 7, 6, 3])

In [4]:
a1+a2

array([ 3, 16, 13, 13, 12])

In [5]:
a1-a2

array([-1,  0, -1,  1,  6])

In [6]:
a1*a2

array([ 2, 64, 42, 42, 27])

In [7]:
a1/a2

array([0.5       , 1.        , 0.85714286, 1.16666667, 3.        ])

In [8]:
ans=a1**2
ans

array([ 1, 64, 36, 49, 81])

In [9]:
np.sqrt(ans)

array([1., 8., 6., 7., 9.])

In [10]:
a3=np.array([1.2,2.5,3.7,4.9])
a3

array([1.2, 2.5, 3.7, 4.9])

In [11]:
np.floor(a3)

array([1., 2., 3., 4.])

In [12]:
np.ceil(a3)

array([2., 3., 4., 5.])

In [13]:
np.around(a3)

array([1., 2., 4., 5.])

Combaining arrarys.

In [14]:
a1

array([1, 8, 6, 7, 9])

In [15]:
a2

array([2, 8, 7, 6, 3])

In [16]:
np.concatenate([a1,a2])

array([1, 8, 6, 7, 9, 2, 8, 7, 6, 3])

spliting arrary

In [17]:
arr=np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [18]:
np.split(arr,6)

[array([1]), array([2]), array([3]), array([4]), array([5]), array([6])]

In [19]:
arr2=np.array([[1,2,3,4,5,6],
               [7,8,9,10,11,12]])
arr2

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [20]:
np.hsplit(arr2,3)

[array([[1, 2],
        [7, 8]]),
 array([[ 3,  4],
        [ 9, 10]]),
 array([[ 5,  6],
        [11, 12]])]

In [21]:
np.vsplit(arr2,2)

[array([[1, 2, 3, 4, 5, 6]]), array([[ 7,  8,  9, 10, 11, 12]])]

Searching in arrary .

In [22]:
a1

array([1, 8, 6, 7, 9])

In [23]:
np.where(a1==7)

(array([3]),)

In [24]:
a3 = np.array([1,3,5,6,3,7,1])
a3

array([1, 3, 5, 6, 3, 7, 1])

In [25]:
np.where(a3==3)

(array([1, 4]),)

In [26]:
np.where(a3>3)

(array([2, 3, 5]),)

In [27]:
arr2

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [28]:
np.where(arr2==5)

(array([0]), array([4]))

In [29]:
arr3=np.array([[1,2,3],[2,5,7],[4,5,2]])
arr3

array([[1, 2, 3],
       [2, 5, 7],
       [4, 5, 2]])

In [30]:
np.where(arr3==3)

(array([0]), array([2]))

Sorting of array

In [31]:
a1

array([1, 8, 6, 7, 9])

In [32]:
np.sort(a1)

array([1, 6, 7, 8, 9])

In [33]:
np

<module 'numpy' from 'c:\\Users\\sosa\\AppData\\Local\\Programs\\Python\\Python314\\Lib\\site-packages\\numpy\\__init__.py'>

In [34]:
arr3

array([[1, 2, 3],
       [2, 5, 7],
       [4, 5, 2]])

In [35]:
np.sort(arr3)

array([[1, 2, 3],
       [2, 5, 7],
       [2, 4, 5]])

Aggragating statical funcation .

In [36]:
a1

array([1, 8, 6, 7, 9])

In [37]:
np.sum(a1)

np.int64(31)

In [38]:
np.mean(a1)

np.float64(6.2)

In [39]:
np.median(a1)

np.float64(7.0)

In [40]:
np.max(a1)

np.int64(9)

In [41]:
np.min(a1)

np.int64(1)

In [42]:
np.std(a1)

np.float64(2.7856776554368237)

In [43]:
np.var(a1)

np.float64(7.76)

In [44]:
arr4=np.array([[1,2,3],[4,5,6]])
arr4

array([[1, 2, 3],
       [4, 5, 6]])

In [45]:
np.sum(arr4)

np.int64(21)

In [46]:
np.sum(arr4,axis=1)

array([ 6, 15])

In [47]:
np.sum(arr4,axis=0)

array([5, 7, 9])